<?php

namespace App\Filament\Resources\BlogArticleResource\Pages;

use App\Filament\Resources\BlogArticleResource;
use App\Filament\Resources\Concerns\MutatesTranslatableFields;
use Filament\Resources\Pages\CreateRecord;

class CreateBlogArticle extends CreateRecord
{
    use MutatesTranslatableFields;

    protected static string $resource = BlogArticleResource::class;

    protected function getTranslatableFields(): array
    {
        return ['title', 'description', 'meta_title', 'meta_description', 'meta_keywords'];
    }

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }

    /**
     * Override slug persistence — BlogArticle slugs are auto-generated by HasSlugs
     * from the title field, so we do not need to persist them manually.
     */
    protected function persistPendingSlugs(): void
    {
        // No-op: slugs are auto-generated by the HasSlugs trait on the model.
    }
}
